//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adatok
    {
        public int id { get; set; }
        public Nullable<int> szobaId { get; set; }
        public int homerseklet { get; set; }
        public int paratartalom { get; set; }
        public int levegoMin { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
    
        public virtual szoba szoba { get; set; }
    }
}
