//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OkosContext : DbContext
    {
        public OkosContext()
            : base("name=OkosContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adatok> adatok { get; set; }
        public virtual DbSet<eszkozok> eszkozok { get; set; }
        public virtual DbSet<futes> futes { get; set; }
        public virtual DbSet<lakas> lakas { get; set; }
        public virtual DbSet<szoba> szoba { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<tobbeszkoz> tobbeszkoz { get; set; }
        public virtual DbSet<tobbfutes> tobbfutes { get; set; }
    }
}
