//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class szoba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public szoba()
        {
            this.adatok = new HashSet<adatok>();
            this.tobbeszkoz = new HashSet<tobbeszkoz>();
            this.tobbfutes = new HashSet<tobbfutes>();
        }
    
        public int id { get; set; }
        public string szobaNev { get; set; }
        public int terulet { get; set; }
        public Nullable<int> lakasID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adatok> adatok { get; set; }
        public virtual lakas lakas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tobbeszkoz> tobbeszkoz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tobbfutes> tobbfutes { get; set; }
    }
}
