//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string felh { get; set; }
        public string jelszo { get; set; }
        public string emial { get; set; }
        public Nullable<int> lakasId { get; set; }
    
        public virtual lakas lakas { get; set; }
    }
}
